# Generated by Django 4.0.5 on 2022-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=12, upload_to='covers/'),
            preserve_default=False,
        ),
    ]
